apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app

spec:
  type: NodePort
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - port: 80 # Target port of the Pods
      nodePort: 30004
